export interface ScrapedPost {
    UID?: string;
    idposts?: number;
    keyword?: string;
    title?: string;
    organization?: string;
    link?: string;
    description?: string;
    date_posted?: Date | string | number;
    city?: string;
    state?: string;
    end_date?: Date | string | number | null;
    salary?: string | number;
    job_type?: string;
    winner?: string | null;
    competition_category?: string;
    job_category?: string;
    address?: string;
    is_deleted?: string | number;
    is_flagged?: string | number;
    type?: string;
    start_date?: Date | string | number;
    published_date?: Date | string | number;
    start_time?: Date | string | number | null;
    author?: string;
    first_name?: string;
    last_name?: string;
    email?: string;
    is_expired?: string;
    is_banned?: number;
    is_winner?: string;
    is_admin?: number;
    ban_message?: string;
    deleted_comment?: string;
    fee?: string | number;
    deadline?: Date | string | number | null;
    writer?: string;
    genre?: string;
  }